---
name: "tagged-release"

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  build-darwin-amd64:
    name: Build darwin (amd64)
    runs-on: macos-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install FoundationDB Client
        run: |
          wget -nv https://github.com/apple/foundationdb/releases/download/7.1.27/FoundationDB-7.1.27_x86_64.pkg -O /tmp/foundationdb.pkg
          sudo installer -pkg /tmp/foundationdb.pkg -target /

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build darwin/amd64 binary
        run: |
          GOOS=darwin GOARCH=amd64 go build -o fdbexplorer-darwin-amd64

      - name: Calculate checksums
        run: |
          shasum -a 256 ./fdbexplorer-darwin-amd64 > fdbexplorer-darwin-amd64.sha256

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-darwin-amd64
          path: |
            fdbexplorer-*

  build-linux:
    name: Build linux
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install FoundationDB Client
        run: |
          wget -nv https://github.com/apple/foundationdb/releases/download/7.1.27/foundationdb-clients_7.1.27-1_amd64.deb -O /tmp/foundationdb-clients.deb
          sudo dpkg -i /tmp/foundationdb-clients.deb

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build linux/amd64 binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o fdbexplorer-linux-amd64

      - name: Calculate checksums
        run: |
          sha256sum ./fdbexplorer-linux-amd64 > fdbexplorer-linux-amd64.sha256

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: |
            fdbexplorer-*

  release:
    name: Release to GitHub
    needs:
      - build-linux
      - build-darwin-amd64
    runs-on: ubuntu-20.04
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Release to GitHub Releases
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *-build/fdbexplorer-*