---
name: "tagged-release"

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install FoundationDB Client
        run: |
          curl https://github.com/apple/foundationdb/releases/download/7.1.22/foundationdb-clients_7.1.22-1_amd64.deb -o foundationdb-clients.deb
          dpkg -i foundationdb-clients.deb

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build linux/amd64 binary
        run: |
          GOOS=linux GOARCH=amd64 go build

      - name: Release to GitHub Releases
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            fdbexplorer